spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
